### PR TITLE
Grafana annotation support

### PR DESCRIPTION
**Pull request by goru97**

### CODE REVIEW

**Comment by GeorgeJahad** [comment]
This code looks fine to me, but in general I prefer minimizing changes to third party libraries.   Clearly, you have to change it a bit, but my preference would be to just have a stripped version of fetchEvents() that retrieves the finder node and does everything else in node.getEvents()

If you were planning to submit these changes back to the open-source graphite-api repo, then I would understand making these changes here.  Otherwise, I think they make more sense in BF.

What do you think?

**Comment by goru97** [comment]
I believe that blueflood finder can only work in conjunction with graphite-api and the changes in graphite-api are only related to getting the timestamps in seconds based on the timezone configuration of the app, I don't want to send extra params like timezone to blueflood unnecessarily. Also, these changes are in accordance with the package structure used in graphite-web so I feel they are placed here correctly.

**Comment by GeorgeJahad** [comment]
The other reason for putting all our changes in the BF section is for ease of testing.  In the past the BF team hasn't been good about creating/maintaining unit tests, so I've been trying to push for decent test coverage with every PR.  

If the tz code were BF we could add tests for it with the other unit tests there.

I know the tz code is straightforward, and the unit test for it fairly trivial, but the team as a whole needs to start developing better habits about unit testing, so that's why I was thinking it would be good to move it.

**Comment by goru97** [comment]
Hey George, This is where this method is previously used https://github.com/rackerlabs/graphite-api/blob/goru97/grafana_annotation_support/graphite_api/app.py#L348

**Comment by GeorgeJahad** [comment]
Since the tz code is copied from elsewhere in graphite-api, I'm ok with not adding unit tests for it.
+1

**Pull request merged**
