### PR TITLE
Grafana annotation support

### PR DESCRIPTION
**Pull request by VinnyQ**
This PR supports /events/get_data for finders which support the __fetch_events__ attribute.

From @usnavi :
I'm an engineer on https://github.com/rackerlabs/blueflood, a multi-tenant TSDB. A while back our team forked a version of graphite-api, and we’d like to explore if our changes are appropriate for the upstream branch. I’d very much like to source upstream to catch all the features and fixes.

This has all the necessary updates from the https://github.com/rackerlabs/graphite-api-old/tree/george/fetch_multi_with_patches branch that we want to carry forward.

### CODE REVIEW

**Comment by VinnyQ** [comment]
@usnavi bam, how's this looking?

**Comment by VinnyQ** [comment]
@goru97 Hi gaurav, can you review and make sure all your changes for grafana annotation support made it into this PR?  We squashed 11 of the grafana_annotation_support commits into 1.

**Comment by usnavi** [comment]
lgtm - we'll need to test this to make sure everything works in the heat template and docker images.

**Comment by goru97** [comment]
+1 to what @usnavi said. Test it and see if it works.

**Pull request merged**
